spring:
  application:
    name: boardVer3
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board2024_v3
    username: root
    password: green502

# ??? ???? ??, ??? ?? ?? ????
# ??????? ??? ??
# : ???? ?? ??

mybatis:
  mapper-locations: mappers/**/*.xml
# ??????? xml? ?? ??
# ????? resources? ?? ??? ?? ?? ????? ??

springdoc:
  swagger-ui:
    path: /swagger
    # ??? ????? ??
# ????? ??? ??? ????? ??